name: Master Branch Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  zip-contents:
    name: Archive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Zip contents
        run: |
          zip -r OS-Job-Portal.zip .
      
      - uses: actions/upload-artifact@v3
        with:
          name: OS-Job-Portal.zip
          path: OS-Job-Portal.zip
  
  policy-scan:
      name: Veracode Static Analysis
      runs-on: ubuntu-latest
      needs: zip-contents
      steps:
        - uses: actions/checkout@v3
        - name: get archive
          uses: actions/download-artifact@v3
          with:
            name: OS-Job-Portal.zip
            path: .
        - name: Veracode Upload and Scan Action Step
          uses: veracode/veracode-uploadandscan-action@master
          id: upload_and_scan
          with:
            appname: 'OS Job Portal'
            version: '${{ github.run_id }}'
            filepath: 'OS-Job-Portal.zip'
            vid: '${{ secrets.VERACODE_API_ID }}'
            vkey: '${{ secrets.VERACODE_API_KEY }}'
  #          scantimeout: 15

# delete-zip:
#   runs-on: ubuntu-latest
#   needs: zip-contents
#   steps:
#     - name: Delete zip file
#       run: |
#         rm OS-Job-Portal.zip